<?php

namespace App\Model;

use JMS\Serializer\Annotation as Serializer;
use JMS\Serializer\Annotation\Discriminator;
use JMS\Serializer\Annotation\XmlDiscriminator;

/**
 * @Discriminator(field="name", map = {
 *     "__fallback": "App\Model\Setter",
 *     "short": "App\Model\Setter\Short",
 *     "category": "App\Model\Setter\Category",
 *     "cost": "App\Model\Setter\Cost",
 *     "weight": "App\Model\Setter\Weight",
 *     "stackable": "App\Model\Setter\Stackable",
 *     "slot": "App\Model\Setter\Slot",
 *     "range": "App\Model\Setter\Range",
 *     "damage": "App\Model\Setter\Damage",
 *     "proficiency": "App\Model\Setter\Proficiency",
 *     "multiclass proficiencies": "App\Model\Setter\Proficiency",
 *     "reload": "App\Model\Setter\Reload",
 *     "keywords": "App\Model\Setter\Keywords",
 *     "valuable": "App\Model\Setter\Valuable",
 *     "type": "App\Model\Setter\Type",
 *     "abbreviation": "App\Model\Setter\Abbreviation",
 *     "url": "App\Model\Setter\Url",
 *     "image": "App\Model\Setter\Image",
 *     "errata": "App\Model\Setter\Errata",
 *     "author": "App\Model\Setter\Author",
 *     "official": "App\Model\Setter\Official",
 *     "core": "App\Model\Setter\Core",
 *     "release": "App\Model\Setter\Release",
 *     "inventory-hidden": "App\Model\Setter\InventoryHidden",
 *     "allow duplicate": "App\Model\Setter\AllowDuplicate",
 *     "strength": "App\Model\Setter\Strength",
 *     "dexterity": "App\Model\Setter\Dexterity",
 *     "constitution": "App\Model\Setter\Constitution",
 *     "intelligence": "App\Model\Setter\Intelligence",
 *     "wisdom": "App\Model\Setter\Wisdom",
 *     "charisma": "App\Model\Setter\Charisma",
 *     "ac": "App\Model\Setter\Ac",
 *     "hp": "App\Model\Setter\Hp",
 *     "speed": "App\Model\Setter\Speed",
 *     "senses": "App\Model\Setter\Senses",
 *     "languages": "App\Model\Setter\Languages",
 *     "skills": "App\Model\Setter\Skills",
 *     "resistances": "App\Model\Setter\Resistances",
 *     "immunities": "App\Model\Setter\Immunities",
 *     "size": "App\Model\Setter\Size",
 *     "alignment": "App\Model\Setter\Alignment",
 *     "challenge": "App\Model\Setter\Challenge",
 *     "traits": "App\Model\Setter\Traits",
 *     "actions": "App\Model\Setter\Actions",
 *     "monster": "App\Model\Setter\Monster",
 *     "speakers": "App\Model\Setter\Speakers",
 *     "script": "App\Model\Setter\Script",
 *     "hd": "App\Model\Setter\Hd",
 *     "setting": "App\Model\Setter\Setting",
 *     "domains": "App\Model\Setter\Domains",
 *     "symbol": "App\Model\Setter\Symbol",
 *     "gender": "App\Model\Setter\Gender",
 *     "armor": "App\Model\Setter\Armor",
 *     "armorClass": "App\Model\Setter\ArmorClass",
 *     "stealth": "App\Model\Setter\Stealth",
 *     "container": "App\Model\Setter\Container",
 *     "versatile": "App\Model\Setter\Versatile",
 *     "standard": "App\Model\Setter\Standard",
 *     "exotic": "App\Model\Setter\Exotic",
 *     "secret": "App\Model\Setter\Secret",
 *     "names": "App\Model\Setter\Names",
 *     "names-format": "App\Model\Setter\NamesFormat",
 *     "height": "App\Model\Setter\Height",
 *     "level": "App\Model\Setter\Level",
 *     "school": "App\Model\Setter\School",
 *     "time": "App\Model\Setter\Time",
 *     "duration": "App\Model\Setter\Duration",
 *     "hasVerbalComponent": "App\Model\Setter\HasVerbalComponent",
 *     "hasSomaticComponent": "App\Model\Setter\HasSomaticComponent",
 *     "hasMaterialComponent": "App\Model\Setter\HasMaterialComponent",
 *     "materialComponent": "App\Model\Setter\MaterialComponent",
 *     "isConcentration": "App\Model\Setter\IsConcentration",
 *     "isRitual": "App\Model\Setter\IsRitual",
 *     "supplement": "App\Model\Setter\Supplement",
 *     "league": "App\Model\Setter\League",
 *     "conditionImmunities": "App\Model\Setter\ConditionImmunities",
 *     "saves": "App\Model\Setter\Saves",
 *     "reactions": "App\Model\Setter\Reactions",
 *     "legal": "App\Model\Setter\Legal",
 *     "information": "App\Model\Setter\Information",
 *     "rarity": "App\Model\Setter\Rarity",
 *     "damage resistances": "App\Model\Setter\DamageResistances",
 *     "damage immunities": "App\Model\Setter\DamageImmunities",
 *     "condition immunities": "App\Model\Setter\ConditionImmunities",
 *     "override": "App\Model\Setter\Override",
 *     "playtest": "App\Model\Setter\Playtest",
 *     "incomplete": "App\Model\Setter\Incomplete",
 *     "sourceUrl": "App\Model\Setter\SourceUrl",
 *     "spellcastingClass": "App\Model\Setter\SpellcastingClass",
 *     "spellcastingAbility": "App\Model\Setter\SpellcastingAbility",
 *     "disabled": "App\Model\Setter\Disabled",
 *     "enhancement": "App\Model\Setter\Enchancement",
 *     "name-format": "App\Model\Setter\NameFormat",
 *     "supports": "App\Model\Setter\Supports",
 *     "attunement": "App\Model\Setter\Attunement",
 *     "cursed": "App\Model\Setter\Cursed",
 *     "charges": "App\Model\Setter\Charges",
 *     "equippable": "App\Model\Setter\Equippable",
 *     "weapon": "App\Model\Setter\Weapon",
 *     "stash": "App\Model\Setter\Stash"
 * })
 * @XmlDiscriminator(attribute=true)
 */
class Setter
{
    /**
     * @Serializer\XmlValue
     */
    public string $value;
}